# Example output written by bigdata_write_spark_defaults.
# The real file contains your actual VDCLOUD_USER value.

spark.master                                   k8s://https://source-code-master.cluster.local:6443
spark.submit.deployMode                        cluster
spark.kubernetes.namespace                     VDCLOUD_USER-priv
spark.kubernetes.authenticate.driver.serviceAccountName spark
spark.kubernetes.container.image               apache/spark:3.5.8-scala2.12-java11-python3-ubuntu
spark.executor.instances                       1
spark.kubernetes.submission.waitAppCompletion  false
spark.kubernetes.driverEnv.HADOOP_USER_NAME    VDCLOUD_USER
spark.executorEnv.HADOOP_USER_NAME             VDCLOUD_USER
spark.kubernetes.file.upload.path              hdfs://hdfs-namenode.default.svc.cluster.local:9000/user/VDCLOUD_USER/.spark-upload
spark.eventLog.enabled                         true
spark.eventLog.dir                             hdfs://hdfs-namenode.default.svc.cluster.local:9000/user/VDCLOUD_USER/logs
spark.history.fs.logDirectory                  hdfs://hdfs-namenode.default.svc.cluster.local:9000/user/VDCLOUD_USER/logs
